# Generated by Django 6.0.2 on 2026-02-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['lieu', 'date'], name='depenses_de_lieu_id_3d2e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['date'], name='depenses_de_date_698f0e_idx'),
        ),
    ]
