# Generated by Django 5.2.11 on 2026-02-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usine", "0002_lotproduction_composition_and_reception_mp"),
        ("depenses", "0003_depense_montant_positive"),
    ]

    operations = [
        migrations.AddField(
            model_name="depense",
            name="production_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="depenses",
                to="usine.lotproduction",
            ),
        ),
    ]
