# Generated by Django 5.2.11 on 2026-03-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_tokens_revoked_at'),
        ('depenses', '0004_depense_production_order'),
        ('usine', '0006_cessionlot_prix_par_sac_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Clé idempotente de création (anti double soumission).', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('lieu', 'idempotency_key'), name='unique_depense_lieu_idempotency_key'),
        ),
    ]
