# Generated by Django 5.2.11 on 2026-03-18 15:55

import depenses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_audit_final_constraints'),
        ('depenses', '0006_categorie_depense_entreprise'),
        ('usine', '0007_audit_final_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='depense',
            name='unique_depense_lieu_idempotency_key',
        ),
        migrations.RenameIndex(
            model_name='categoriedepense',
            new_name='depenses_ca_entrepr_af4889_idx',
            old_name='depenses_ca_entrep_5c3c2b_idx',
        ),
        migrations.AddField(
            model_name='depense',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='core.entreprise'),
        ),
        migrations.AlterField(
            model_name='categoriedepense',
            name='entreprise',
            field=models.ForeignKey(default=depenses.models._default_entreprise_id, on_delete=django.db.models.deletion.PROTECT, related_name='categories_depenses', to='core.entreprise'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='core.lieu'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['entreprise', 'date'], name='depenses_de_entrepr_d4031b_idx'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('entreprise', 'idempotency_key'), name='unique_depense_entreprise_idempotency_key'),
        ),
    ]
