# Generated by Django 5.2.11 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_lieu_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("comptable", "Comptable"),
                    ("usine", "Usine"),
                    ("boutique", "Boutique"),
                ],
                default="boutique",
                max_length=20,
            ),
        ),
    ]
