# Generated by Django 5.2.11 on 2026-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_role_usine'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='adresse',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lieu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
