# Generated by Django 5.2.11 on 2026-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lieu_adresse_lieu_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRevocationEpoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revoked_before', models.DateTimeField(help_text='Tout token JWT émis à ou avant cette date/heure est invalide.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Époque de révocation JWT',
                'verbose_name_plural': 'Époques de révocation JWT',
                'ordering': ['-revoked_before'],
            },
        ),
    ]
