# Generated by Django 5.2.11 on 2026-02-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_token_revocation_epoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='core.entreprise'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lieu',
            field=models.OneToOneField(blank=True, help_text='Pour rôle boutique : le magasin lié à ce compte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compte_boutique', to='core.lieu'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lieux', to='core.entreprise'),
        ),
    ]
