# Generated by Django 5.2.11 on 2026-02-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_protect_cascade_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('comptable', 'Comptable'), ('usine', 'Usine'), ('boutique', 'Boutique')], db_index=True, default='boutique', max_length=20),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='type_lieu',
            field=models.CharField(choices=[('usine', 'Usine'), ('magasin', 'Magasin')], db_index=True, max_length=20),
        ),
    ]
