# Generated by Django 5.2.11 on 2026-02-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_missing_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='mouture_enabled',
            field=models.BooleanField(default=True, help_text='Ce lieu propose-t-il le service de mouture (broyage de grain) ?'),
        ),
    ]
