# Generated by Django 5.2.11 on 2026-03-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_mpsl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('supreme_admin', 'Supreme Admin'), ('admin', 'Admin'), ('daf', 'DAF'), ('comptable', 'Comptable'), ('usine', 'Usine'), ('boutique', 'Boutique'), ('mpsl', 'MPSL')], db_index=True, default='boutique', max_length=20),
        ),
    ]
