# Generated by Django 5.2.11 on 2026-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lieu_mouture_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tokens_revoked_at',
            field=models.DateTimeField(blank=True, help_text="Si renseigné, tout token JWT émis AVANT cette date est invalidé. Mis à jour automatiquement lors d'un changement de mot de passe ou d'une désactivation.", null=True),
        ),
    ]
