# Generated by Django 5.2.11 on 2026-03-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_tokens_revoked_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lieu',
            constraint=models.CheckConstraint(condition=models.Q(('prix_mouture_defaut__isnull', True), ('prix_mouture_defaut__gt', 0), _connector='OR'), name='lieu_prix_mouture_defaut_positif'),
        ),
        migrations.AddConstraint(
            model_name='lieu',
            constraint=models.CheckConstraint(condition=models.Q(('prix_mouture_max__isnull', True), ('prix_mouture_max__gt', 0), _connector='OR'), name='lieu_prix_mouture_max_positif'),
        ),
    ]
