# Generated by Django 5.2.11 on 2026-03-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_collecteur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('endpoint', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'En cours'), ('success', 'Succès')], default='processing', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Clé d'idempotency",
                'verbose_name_plural': "Clés d'idempotency",
                'indexes': [models.Index(fields=['key', 'endpoint'], name='idem_key_endpoint_idx'), models.Index(fields=['created_at'], name='idem_created_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'endpoint'), name='unique_idem_key_endpoint')],
            },
        ),
    ]
