# Generated by Django 5.2.11 on 2026-03-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_db_triggers'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='idempotencykey',
            name='idem_key_endpoint_idx',
        ),
    ]
