# Generated by Django 6.0.2 on 2026-02-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['lieu', 'date'], name='ventes_tick_lieu_id_193297_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['date'], name='ventes_tick_date_2889f0_idx'),
        ),
    ]
