# Generated by Django 5.2.11 on 2026-02-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_facture_lignefacture'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facture',
            new_name='ventes_fact_lieu_id_cf0713_idx',
            old_name='ventes_factu_lieu_id_a42f9b_idx',
        ),
        migrations.RenameIndex(
            model_name='facture',
            new_name='ventes_fact_date_92c2e9_idx',
            old_name='ventes_factu_date_8c8aa2_idx',
        ),
    ]
