# Generated by Django 5.2.11 on 2026-02-26 16:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_add_missing_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cout_mouture',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Coût total mouture'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant total (produits + mouture)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mouture',
            field=models.BooleanField(default=False, verbose_name='Mouture demandée'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prix_mouture_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix mouture / kg'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prix_mouture_sac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix mouture / sac'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prix_mouture_tonne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix mouture / tonne'),
        ),
    ]
