# Generated by Django 5.2.11 on 2026-02-27 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lieu_mouture_enabled'),
        ('ventes', '0008_ticket_produit_apporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Réimpression de ticket',
                'verbose_name_plural': 'Réimpressions de tickets',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['numero'], name='ventes_tick_numero_280ce2_idx'),
        ),
        migrations.AddField(
            model_name='ticketreprint',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_reprints', to='core.lieu'),
        ),
        migrations.AddField(
            model_name='ticketreprint',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reprints', to='ventes.ticket'),
        ),
        migrations.AddField(
            model_name='ticketreprint',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_reprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ticketreprint',
            index=models.Index(fields=['ticket', 'date_heure'], name='ventes_tick_ticket__0f7709_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketreprint',
            index=models.Index(fields=['utilisateur', 'date_heure'], name='ventes_tick_utilisa_ce4c15_idx'),
        ),
    ]
