# Generated by Django 5.2.11 on 2026-02-28 00:00

import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0009_ticket_reprint_and_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Cle idempotente de creation (anti double soumission).",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("lieu", "idempotency_key"),
                name="unique_ticket_lieu_idempotency_key",
            ),
        ),
    ]
