# Generated by Django 5.2.11 on 2026-03-18 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_tokens_revoked_at'),
        ('produits', '0008_produit_poids_par_sac'),
        ('ventes', '0011_ticket_quantite_apportee_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='facture_total_positif'),
        ),
        migrations.AddConstraint(
            model_name='lignefacture',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='lignefacture_quantite_positive'),
        ),
        migrations.AddConstraint(
            model_name='lignefacture',
            constraint=models.CheckConstraint(condition=models.Q(('prix_unitaire__gte', 0)), name='lignefacture_prix_unitaire_positif'),
        ),
        migrations.AddConstraint(
            model_name='lignevente',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='lignevente_quantite_positive'),
        ),
        migrations.AddConstraint(
            model_name='lignevente',
            constraint=models.CheckConstraint(condition=models.Q(('prix_unitaire__gte', 0)), name='lignevente_prix_unitaire_positif'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total__gte', 0)), name='ticket_montant_total_positif'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('cout_mouture__gte', 0)), name='ticket_cout_mouture_positif'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_apportee_client__gte', 0)), name='ticket_quantite_apportee_positif'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('prix_mouture_kg__isnull', True), ('prix_mouture_kg__gte', 0), _connector='OR'), name='ticket_prix_mouture_kg_positif'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('prix_mouture_tonne__isnull', True), ('prix_mouture_tonne__gte', 0), _connector='OR'), name='ticket_prix_mouture_tonne_positif'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('prix_mouture_sac__isnull', True), ('prix_mouture_sac__gte', 0), _connector='OR'), name='ticket_prix_mouture_sac_positif'),
        ),
    ]
