# Generated by Django 5.2.11 on 2026-03-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0012_audit_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacture',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='ventes.facture'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='ventes.ticket'),
        ),
    ]
