# Generated by Django 5.2.11 on 2026-03-21 06:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_audit_final_constraints'),
        ('finance', '0003_cash_credit_collecte_fournisseur'),
        ('ventes', '0013_finance_constraints_cascade_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client requis pour vente à crédit ou partielle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='finance.clientfinance'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='montant_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Argent réellement encaissé lors de la vente.', max_digits=14),
        ),
        migrations.AddField(
            model_name='ticket',
            name='montant_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant dû par le client (créance).', max_digits=14),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_vente',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Crédit'), ('partiel', 'Partiel')], db_index=True, default='cash', help_text='Cash = encaissé; Crédit = tout à créer; Partiel = acompte + solde.', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('montant_cash__gte', 0)), name='ticket_montant_cash_positif'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('montant_credit__gte', 0)), name='ticket_montant_credit_positif'),
        ),
    ]
