# Generated by Django 5.2.11 on 2026-03-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0018_lignevente_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='unite',
            field=models.CharField(blank=True, default='', help_text='Unité de la ligne (ex. kg, sac).', max_length=20),
        ),
    ]
