# Generated by Django 5.2.11 on 2026-03-17 22:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_finance_app_et_nouveaux_roles'),
        ('produits', '0007_alter_produit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients_finance', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Client (finance)',
                'verbose_name_plural': 'Clients (finance)',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Creancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_creancier', models.CharField(choices=[('fournisseur', 'Fournisseur'), ('banque', 'Banque'), ('partenaire', 'Partenaire'), ('autre', 'Autre')], default='fournisseur', max_length=20)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creanciers', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Créancier',
                'verbose_name_plural': 'Créanciers',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom ou objet du prêt', max_length=255)),
                ('banque', models.CharField(max_length=255)),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('taux_interet', models.DecimalField(blank=True, decimal_places=2, help_text='Taux annuel en %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('date_debut', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rembourse', 'Remboursé')], default='en_cours', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalCreance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('solde', 'Soldé')], default='en_cours', max_length=10)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journaux', to='finance.clientfinance')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de créance',
                'verbose_name_plural': 'Journaux de créances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Référence facture fournisseur', max_length=100)),
                ('description', models.TextField()),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('solde', 'Soldé')], default='en_cours', max_length=10)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Date de verrouillage (soldé)', null=True)),
                ('creancier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journaux', to='finance.creancier')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal payable',
                'verbose_name_plural': 'Journaux payables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCreance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='finance.journalcreance')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Ligne de créance',
                'verbose_name_plural': 'Lignes de créances',
            },
        ),
        migrations.CreateModel(
            name='PaiementCreance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='finance.journalcreance')),
            ],
            options={
                'verbose_name': 'Paiement créance',
                'verbose_name_plural': 'Paiements créances',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='finance.journalpayable')),
            ],
            options={
                'verbose_name': 'Paiement payable',
                'verbose_name_plural': 'Paiements payables',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('budget_initial', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='en_cours', max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepotProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='finance.projet')),
            ],
            options={
                'verbose_name': 'Dépôt projet',
                'verbose_name_plural': 'Dépôts projets',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepenseProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='finance.projet')),
            ],
            options={
                'verbose_name': 'Dépense projet',
                'verbose_name_plural': 'Dépenses projets',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementEmprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('emprunt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='finance.emprunt')),
            ],
            options={
                'verbose_name': "Remboursement d'emprunt",
                'verbose_name_plural': "Remboursements d'emprunts",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaisseSupremeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caisse_transactions', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Transaction caisse suprême',
                'verbose_name_plural': 'Transactions caisse suprême',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['entreprise', 'date'], name='caisse_ent_date_idx'), models.Index(fields=['entreprise', 'type_transaction'], name='caisse_ent_type_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='clientfinance',
            index=models.Index(fields=['entreprise', 'nom'], name='clientfin_ent_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='creancier',
            index=models.Index(fields=['entreprise', 'nom'], name='creancier_ent_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['entreprise', 'statut'], name='emprunt_ent_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='journalcreance',
            index=models.Index(fields=['client', 'statut'], name='jcreance_client_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='journalcreance',
            index=models.Index(fields=['statut', 'date_echeance'], name='jcreance_statut_echeance_idx'),
        ),
        migrations.AddIndex(
            model_name='journalpayable',
            index=models.Index(fields=['creancier', 'statut'], name='jpayable_creancier_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='journalpayable',
            index=models.Index(fields=['statut', 'date_echeance'], name='jpayable_statut_echeance_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementcreance',
            index=models.Index(fields=['journal', 'date'], name='paiement_creance_jrn_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementpayable',
            index=models.Index(fields=['journal', 'date'], name='paiement_payable_jrn_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['entreprise', 'statut'], name='projet_ent_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='depotprojet',
            index=models.Index(fields=['projet', 'date'], name='depot_projet_date_idx'),
        ),
        migrations.AddIndex(
            model_name='depenseprojet',
            index=models.Index(fields=['projet', 'date'], name='depense_projet_date_idx'),
        ),
        migrations.AddIndex(
            model_name='remboursementemprunt',
            index=models.Index(fields=['emprunt', 'date'], name='remboursement_emprunt_date_idx'),
        ),
    ]
