# Generated by Django 5.2.11 on 2026-03-18 08:21

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_tokens_revoked_at'),
        ('finance', '0001_finance_app_et_nouveaux_roles'),
        ('produits', '0008_produit_poids_par_sac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='taux_interet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux annuel en % (0–100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='projet',
            name='budget_initial',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='caissesupremetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gte', Decimal('0.01'))), name='caisse_montant_min'),
        ),
        migrations.AddConstraint(
            model_name='depenseprojet',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gte', Decimal('0.01'))), name='depense_projet_montant_min'),
        ),
        migrations.AddConstraint(
            model_name='depotprojet',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gte', Decimal('0.01'))), name='depot_projet_montant_min'),
        ),
        migrations.AddConstraint(
            model_name='emprunt',
            constraint=models.CheckConstraint(condition=models.Q(('montant_initial__gte', Decimal('0.01'))), name='emprunt_montant_initial_min'),
        ),
        migrations.AddConstraint(
            model_name='emprunt',
            constraint=models.CheckConstraint(condition=models.Q(('montant_rembourse__gte', 0)), name='emprunt_montant_rembourse_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='emprunt',
            constraint=models.CheckConstraint(condition=models.Q(('taux_interet__isnull', True), ('taux_interet__gte', 0), _connector='OR'), name='emprunt_taux_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='emprunt',
            constraint=models.CheckConstraint(condition=models.Q(('taux_interet__isnull', True), ('taux_interet__lte', 100), _connector='OR'), name='emprunt_taux_max_100'),
        ),
        migrations.AddConstraint(
            model_name='journalcreance',
            constraint=models.CheckConstraint(condition=models.Q(('montant_initial__gte', Decimal('0.01'))), name='jcreance_montant_initial_min'),
        ),
        migrations.AddConstraint(
            model_name='journalcreance',
            constraint=models.CheckConstraint(condition=models.Q(('montant_paye__gte', 0)), name='jcreance_montant_paye_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='journalpayable',
            constraint=models.CheckConstraint(condition=models.Q(('montant_initial__gte', Decimal('0.01'))), name='jpayable_montant_initial_min'),
        ),
        migrations.AddConstraint(
            model_name='journalpayable',
            constraint=models.CheckConstraint(condition=models.Q(('montant_paye__gte', 0)), name='jpayable_montant_paye_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='lignecreance',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='lignecreance_quantite_positive'),
        ),
        migrations.AddConstraint(
            model_name='lignecreance',
            constraint=models.CheckConstraint(condition=models.Q(('prix_unitaire__gte', 0)), name='lignecreance_prix_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='paiementcreance',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gte', Decimal('0.01'))), name='paiement_creance_montant_min'),
        ),
        migrations.AddConstraint(
            model_name='paiementpayable',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gte', Decimal('0.01'))), name='paiement_payable_montant_min'),
        ),
        migrations.AddConstraint(
            model_name='projet',
            constraint=models.CheckConstraint(condition=models.Q(('budget_initial__gte', Decimal('0.01'))), name='projet_budget_initial_positif'),
        ),
        migrations.AddConstraint(
            model_name='remboursementemprunt',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gte', Decimal('0.01'))), name='remboursement_montant_min'),
        ),
    ]
