# Generated by Django 5.2.11 on 2026-03-21 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_audit_final_constraints'),
        ('finance', '0002_finance_constraints_cascade_protect'),
        ('ventes', '0013_finance_constraints_cascade_protect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollecteArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collecte', models.DateField(help_text='Date du passage.')),
                ('montant_trouve', models.DecimalField(decimal_places=2, help_text='Argent trouvé dans la caisse boutique.', max_digits=14)),
                ('montant_pris', models.DecimalField(decimal_places=2, help_text='Argent emporté par le collectionneur.', max_digits=14)),
                ('montant_laisse', models.DecimalField(decimal_places=2, help_text='Argent laissé en caisse = montant_trouve - montant_pris (auto).', max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collecte argent',
                'verbose_name_plural': 'Collectes argent',
                'ordering': ['-date_collecte', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='journalcreance',
            name='lieu',
            field=models.ForeignKey(blank=True, help_text='Boutique source de la créance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creances', to='core.lieu'),
        ),
        migrations.AddField(
            model_name='journalcreance',
            name='ticket',
            field=models.OneToOneField(blank=True, help_text='Ticket de vente ayant généré cette créance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creance', to='ventes.ticket'),
        ),
        migrations.AddIndex(
            model_name='journalcreance',
            index=models.Index(fields=['lieu', 'statut'], name='jcreance_lieu_statut_idx'),
        ),
        migrations.AddField(
            model_name='collecteargent',
            name='collecteur',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant effectué la collecte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collecteargent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collecteargent',
            name='depot_banque',
            field=models.ForeignKey(blank=True, help_text='Transaction banque issue de ce dépôt (facultatif).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_source', to='finance.caissesupremetransaction'),
        ),
        migrations.AddField(
            model_name='collecteargent',
            name='lieu',
            field=models.ForeignKey(help_text='Boutique visitée.', limit_choices_to={'type_lieu': 'magasin'}, on_delete=django.db.models.deletion.PROTECT, related_name='collectes', to='core.lieu'),
        ),
        migrations.AddIndex(
            model_name='collecteargent',
            index=models.Index(fields=['lieu', 'date_collecte'], name='collecte_lieu_date_idx'),
        ),
        migrations.AddIndex(
            model_name='collecteargent',
            index=models.Index(fields=['date_collecte'], name='collecte_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='collecteargent',
            constraint=models.CheckConstraint(condition=models.Q(('montant_trouve__gte', 0)), name='collecte_trouve_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='collecteargent',
            constraint=models.CheckConstraint(condition=models.Q(('montant_pris__gte', 0)), name='collecte_pris_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='collecteargent',
            constraint=models.CheckConstraint(condition=models.Q(('montant_laisse__gte', 0)), name='collecte_laisse_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='collecteargent',
            constraint=models.CheckConstraint(condition=models.Q(('montant_pris__lte', models.F('montant_trouve'))), name='collecte_pris_lte_trouve'),
        ),
    ]
