# Generated by Django 5.2.11 on 2026-03-22 14:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_collecteur_role'),
        ('finance', '0003_cash_credit_collecte_fournisseur'),
        ('ventes', '0019_alter_lignevente_unite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalcreance',
            name='correction_caisse',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Montant retranché de la caisse boutique lors de la création (correction d'une vente mal enregistrée).", max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='journalcreance',
            constraint=models.CheckConstraint(condition=models.Q(('correction_caisse__gte', 0)), name='jcreance_correction_caisse_non_negatif'),
        ),
    ]
