# Generated by Django 5.2.11 on 2026-03-22 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_collecteur_role'),
        ('finance', '0004_correction_caisse_creance'),
        ('ventes', '0019_alter_lignevente_unite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalcreance',
            constraint=models.CheckConstraint(condition=models.Q(('correction_caisse__lte', models.F('montant_initial'))), name='jcreance_correction_caisse_max_montant_initial'),
        ),
    ]
