# Generated by Django 5.2.11 on 2026-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_correction_caisse_max_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfinance',
            name='interet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientfinance',
            name='statut',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
