# Generated by Django 5.2.11 on 2026-03-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_collecteur_role'),
        ('finance', '0006_client_statut_interet'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfinance',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_finance', to='core.lieu'),
        ),
    ]
