# Generated by Django 5.2.11 on 2026-03-24 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_clientfinance_lieu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creancier',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('pending', 'En attente de validation')], default='pending', help_text="Statut du créancier. 'pending' = en attente de validation par admin.", max_length=20),
        ),
        migrations.AddConstraint(
            model_name='journalpayable',
            constraint=models.CheckConstraint(condition=models.Q(('montant_paye__lte', models.F('montant_initial'))), name='jpayable_montant_paye_max'),
        ),
    ]
