# Generated by Django 5.2.11 on 2026-02-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_customuser_role_usine"),
        ("inventaire", "0003_stock_inventaire__produit_d0c0c9_idx_and_more"),
        ("produits", "0002_produit_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="LotProduction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom_lot", models.CharField(max_length=100, unique=True)),
                ("quantite_produite", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cout_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lieu_usine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots_production",
                        to="core.lieu",
                    ),
                ),
                (
                    "produit_fini",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots_production",
                        to="produits.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot de production",
                "verbose_name_plural": "Lots de production",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransfertCession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=12)),
                ("prix_cession_unitaire", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cessions_reception",
                        to="core.lieu",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cessions",
                        to="usine.lotproduction",
                    ),
                ),
                (
                    "transfert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cessions",
                        to="inventaire.transfert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert de cession",
                "verbose_name_plural": "Transferts de cession",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompositionLot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cout_unitaire", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compositions",
                        to="usine.lotproduction",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilisations_lot",
                        to="produits.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composition de lot",
                "verbose_name_plural": "Compositions de lots",
            },
        ),
        migrations.AddConstraint(
            model_name="lotproduction",
            constraint=models.CheckConstraint(condition=models.Q(("quantite_produite__gt", 0)), name="lot_quantite_positive"),
        ),
        migrations.AddConstraint(
            model_name="lotproduction",
            constraint=models.CheckConstraint(condition=models.Q(("cout_total__gte", 0)), name="lot_cout_non_negatif"),
        ),
        migrations.AddIndex(
            model_name="lotproduction",
            index=models.Index(fields=["lieu_usine", "created_at"], name="usine_lotpr_lieu_us_58ac85_idx"),
        ),
        migrations.AddIndex(
            model_name="lotproduction",
            index=models.Index(fields=["produit_fini", "created_at"], name="usine_lotpr_produit_7e10c6_idx"),
        ),
        migrations.AddConstraint(
            model_name="transfertcession",
            constraint=models.CheckConstraint(condition=models.Q(("quantite__gt", 0)), name="cession_quantite_positive"),
        ),
        migrations.AddConstraint(
            model_name="transfertcession",
            constraint=models.CheckConstraint(condition=models.Q(("prix_cession_unitaire__gte", 0)), name="cession_prix_non_negatif"),
        ),
        migrations.AddIndex(
            model_name="transfertcession",
            index=models.Index(fields=["lot", "created_at"], name="usine_trans_lot_id_ce428d_idx"),
        ),
        migrations.AddIndex(
            model_name="transfertcession",
            index=models.Index(fields=["boutique", "created_at"], name="usine_trans_boutiqu_c85e13_idx"),
        ),
        migrations.AddConstraint(
            model_name="compositionlot",
            constraint=models.CheckConstraint(condition=models.Q(("quantite__gt", 0)), name="composition_quantite_positive"),
        ),
        migrations.AddConstraint(
            model_name="compositionlot",
            constraint=models.CheckConstraint(condition=models.Q(("cout_unitaire__gte", 0)), name="composition_cout_non_negatif"),
        ),
        migrations.AddConstraint(
            model_name="compositionlot",
            constraint=models.UniqueConstraint(fields=("lot", "matiere"), name="unique_matiere_par_lot"),
        ),
    ]
