# Generated by Django 5.2.11 on 2026-02-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_customuser_role_usine"),
        ("usine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotproduction",
            name="composition",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lotproduction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lots_crees",
                to="core.customuser",
            ),
        ),
        migrations.CreateModel(
            name="ReceptionMatierePremiere",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("supplier", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receptions_mp",
                        to="core.customuser",
                    ),
                ),
                (
                    "lieu_usine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptions_mp",
                        to="core.lieu",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptions_mp",
                        to="produits.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réception matière première",
                "verbose_name_plural": "Réceptions matières premières",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="receptionmatierepremiere",
            constraint=models.CheckConstraint(condition=models.Q(("quantite__gt", 0)), name="reception_mp_quantite_positive"),
        ),
        migrations.AddConstraint(
            model_name="receptionmatierepremiere",
            constraint=models.CheckConstraint(condition=models.Q(("unit_price__gte", 0)), name="reception_mp_prix_non_negatif"),
        ),
        migrations.AddIndex(
            model_name="receptionmatierepremiere",
            index=models.Index(fields=["lieu_usine", "created_at"], name="usine_recep_lieu_us_b39dfa_idx"),
        ),
        migrations.AddIndex(
            model_name="receptionmatierepremiere",
            index=models.Index(fields=["produit", "created_at"], name="usine_recep_produit_4a3098_idx"),
        ),
    ]
