# Generated by Django 5.2.11 on 2026-02-24 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lieu_adresse_lieu_is_active'),
        ('inventaire', '0007_transfertinterusine'),
        ('usine', '0003_simplify_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertInterUsine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_sacs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nombre de sacs transférés')),
                ('poids_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Poids total transféré')),
                ('prix_par_sac', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix par sac')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transfert inter-usines',
                'verbose_name_plural': 'Transferts inter-usines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='lotproduction',
            new_name='usine_lotpr_lieu_us_57eae2_idx',
            old_name='usine_lotpr_lieu_us_58ac85_idx',
        ),
        migrations.RenameIndex(
            model_name='lotproduction',
            new_name='usine_lotpr_produit_15354d_idx',
            old_name='usine_lotpr_produit_7e10c6_idx',
        ),
        migrations.RenameIndex(
            model_name='transfertcession',
            new_name='usine_trans_lot_id_01c2af_idx',
            old_name='usine_trans_lot_id_ce428d_idx',
        ),
        migrations.RenameIndex(
            model_name='transfertcession',
            new_name='usine_trans_boutiqu_19a5ec_idx',
            old_name='usine_trans_boutiqu_c85e13_idx',
        ),
        migrations.AlterField(
            model_name='lotproduction',
            name='quantite_sacs',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nombre de sacs'),
        ),
        migrations.AlterField(
            model_name='transfertcession',
            name='prix_par_sac',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente par sac'),
        ),
        migrations.AlterField(
            model_name='transfertcession',
            name='quantite_sacs',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nombre de sacs transférés'),
        ),
        migrations.AddField(
            model_name='transfertinterusine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_inter_usine_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertinterusine',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_inter_usine', to='usine.lotproduction'),
        ),
        migrations.AddField(
            model_name='transfertinterusine',
            name='transfert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_usine_cessions', to='inventaire.transfert'),
        ),
        migrations.AddField(
            model_name='transfertinterusine',
            name='usine_destination',
            field=models.ForeignKey(limit_choices_to={'type_lieu': 'usine'}, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_inter_usine_entrants', to='core.lieu'),
        ),
        migrations.AddConstraint(
            model_name='transfertinterusine',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_sacs__gt', 0)), name='inter_usine_quantite_sacs_positive'),
        ),
        migrations.AddConstraint(
            model_name='transfertinterusine',
            constraint=models.CheckConstraint(condition=models.Q(('prix_par_sac__gte', 0)), name='inter_usine_prix_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='transfertinterusine',
            constraint=models.CheckConstraint(condition=models.Q(('poids_total__gte', 0)), name='inter_usine_poids_non_negatif'),
        ),
    ]
