# Generated by Django 5.2.11 on 2026-02-24 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_missing_indexes'),
        ('inventaire', '0007_transfertinterusine'),
        ('usine', '0004_transfertinterusine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transfertinterusine',
            index=models.Index(fields=['lot', 'created_at'], name='usine_trans_lot_id_e315d4_idx'),
        ),
        migrations.AddIndex(
            model_name='transfertinterusine',
            index=models.Index(fields=['usine_destination', 'created_at'], name='usine_trans_usine_d_50accd_idx'),
        ),
        migrations.AddIndex(
            model_name='transfertinterusine',
            index=models.Index(fields=['created_at'], name='usine_trans_created_bc97d1_idx'),
        ),
    ]
