# Generated by Django 5.2.11 on 2026-03-18 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_audit_final_constraints'),
        ('produits', '0009_audit_final_constraints'),
        ('usine', '0006_cessionlot_prix_par_sac_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotproduction',
            name='nom_lot',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='lotproduction',
            constraint=models.UniqueConstraint(fields=('lieu_usine', 'nom_lot'), name='unique_nom_lot_par_usine'),
        ),
    ]
