# Generated by Django 6.0.2 on 2026-02-03 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventaire', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatUsine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats_usine', to='core.lieu')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats_usine', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Achat usine',
                'verbose_name_plural': 'Achats usine',
                'ordering': ['-date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='achatusine_quantite_positive')],
            },
        ),
    ]
