# Generated by Django 6.0.2 on 2026-02-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventaire', '0002_add_achatusine'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['produit', 'lieu'], name='inventaire__produit_d0c0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['lieu'], name='inventaire__lieu_id_211900_idx'),
        ),
        migrations.AddIndex(
            model_name='transfert',
            index=models.Index(fields=['date'], name='inventaire__date_4fe379_idx'),
        ),
        migrations.AddIndex(
            model_name='transfert',
            index=models.Index(fields=['from_lieu', 'date'], name='inventaire__from_li_41a85c_idx'),
        ),
        migrations.AddIndex(
            model_name='transfert',
            index=models.Index(fields=['to_lieu', 'date'], name='inventaire__to_lieu_9b858e_idx'),
        ),
    ]
