# Generated by Django 5.2.11 on 2026-02-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usine", "0002_lotproduction_composition_and_reception_mp"),
        ("inventaire", "0003_stock_inventaire__produit_d0c0c9_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mouvementstock",
            name="production_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements_transfert",
                to="usine.lotproduction",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name="mouvementstock",
            constraint=models.CheckConstraint(condition=models.Q(("unit_price__gte", 0)), name="mouvement_unit_price_non_negatif"),
        ),
    ]
