# Generated by Django 5.2.11 on 2026-02-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0006_achatusine_simplify'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='achatusine',
            new_name='inventaire__lieu_id_1b90e7_idx',
            old_name='inventaire_achatusine_lieu_date_idx',
        ),
    ]
