# Generated by Django 5.2.11 on 2026-03-10 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0007_transfertinterusine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-id'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
