# Generated by Django 5.2.11 on 2026-03-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0010_achatmpsl_produit_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
