# Generated by Django 5.2.11 on 2026-03-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0011_audit_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='transfert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='inventaire.transfert'),
        ),
    ]
