# Generated by Django 5.2.11 on 2026-03-21 06:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_cash_credit_collecte_fournisseur'),
        ('inventaire', '0012_finance_constraints_cascade_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatmpsl',
            name='fournisseur',
            field=models.ForeignKey(blank=True, help_text='Fournisseur source de cet achat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_mpsl', to='finance.creancier'),
        ),
        migrations.AddField(
            model_name='achatmpsl',
            name='journal_payable',
            field=models.OneToOneField(blank=True, help_text='Journal de dette fournisseur auto-créé si crédit ou partiel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achat_mpsl', to='finance.journalpayable'),
        ),
        migrations.AddField(
            model_name='achatmpsl',
            name='montant_paye_initial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Acompte versé si type_paiement=partiel.', max_digits=14),
        ),
        migrations.AddField(
            model_name='achatmpsl',
            name='type_paiement',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Crédit'), ('partiel', 'Partiel')], default='cash', help_text='Cash = payé immédiatement; Crédit = dette totale; Partiel = acompte.', max_length=10),
        ),
    ]
