# Generated by Django 5.2.11 on 2026-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
    ]
