# Generated by Django 5.2.11 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="category",
            field=models.CharField(
                choices=[("raw_material", "Matière première"), ("finished", "Produit fini")],
                default="finished",
                max_length=20,
            ),
        ),
    ]
