# Generated by Django 5.2.11 on 2026-02-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_produit_categorie_nullable'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom'], name='produits_pr_nom_fdcfc7_idx'),
        ),
    ]
