# Generated by Codex on 2026-02-28
from django.db import migrations, models
import django.db.models.deletion


def backfill_produits_par_entreprise(apps, schema_editor):
    from django.db.models import Q

    Entreprise = apps.get_model("core", "Entreprise")
    Produit = apps.get_model("produits", "Produit")
    Stock = apps.get_model("inventaire", "Stock")
    MouvementStock = apps.get_model("inventaire", "MouvementStock")
    LotProduction = apps.get_model("usine", "LotProduction")
    LigneVente = apps.get_model("ventes", "LigneVente")
    LigneFacture = apps.get_model("ventes", "LigneFacture")

    default_ent = Entreprise.objects.order_by("id").first()
    if default_ent is None:
        default_ent = Entreprise.objects.create(nom="ENTREPRISE-DEFAULT")

    def entreprises_utilisant_produit(produit_id):
        ent_ids = set(
            Stock.objects.filter(produit_id=produit_id).values_list("lieu__entreprise_id", flat=True)
        )
        ent_ids.update(
            LotProduction.objects.filter(produit_fini_id=produit_id).values_list("lieu_usine__entreprise_id", flat=True)
        )
        ent_ids.update(
            LigneVente.objects.filter(produit_id=produit_id).values_list("ticket__lieu__entreprise_id", flat=True)
        )
        ent_ids.update(
            LigneFacture.objects.filter(produit_id=produit_id).values_list("facture__lieu__entreprise_id", flat=True)
        )
        ent_ids.update(
            MouvementStock.objects.filter(produit_id=produit_id).values_list("transfert__from_lieu__entreprise_id", flat=True)
        )
        ent_ids.update(
            MouvementStock.objects.filter(produit_id=produit_id).values_list("transfert__to_lieu__entreprise_id", flat=True)
        )
        ent_ids = sorted(e for e in ent_ids if e)
        return ent_ids or [default_ent.id]

    for produit in Produit.objects.all().iterator():
        ent_ids = entreprises_utilisant_produit(produit.id)
        primary_ent_id = ent_ids[0]

        Produit.objects.filter(pk=produit.pk).update(entreprise_id=primary_ent_id)

        for ent_id in ent_ids[1:]:
            clone_code = produit.code
            if clone_code:
                suffix = 1
                while Produit.objects.filter(entreprise_id=ent_id, code=clone_code).exists():
                    clone_code = f"{produit.code}-E{ent_id}-{suffix}"
                    suffix += 1

            clone = Produit.objects.create(
                entreprise_id=ent_id,
                categorie_id=produit.categorie_id,
                nom=produit.nom,
                code=clone_code,
                category=produit.category,
                unite=produit.unite,
            )

            Stock.objects.filter(produit_id=produit.id, lieu__entreprise_id=ent_id).update(produit_id=clone.id)
            LotProduction.objects.filter(produit_fini_id=produit.id, lieu_usine__entreprise_id=ent_id).update(
                produit_fini_id=clone.id
            )
            LigneVente.objects.filter(produit_id=produit.id, ticket__lieu__entreprise_id=ent_id).update(
                produit_id=clone.id
            )
            LigneFacture.objects.filter(produit_id=produit.id, facture__lieu__entreprise_id=ent_id).update(
                produit_id=clone.id
            )
            MouvementStock.objects.filter(produit_id=produit.id).filter(
                Q(transfert__from_lieu__entreprise_id=ent_id) | Q(transfert__to_lieu__entreprise_id=ent_id)
            ).update(produit_id=clone.id)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_lieu_mouture_enabled"),
        ("produits", "0004_ticket_reprint_and_indexes"),
        ("inventaire", "0007_transfertinterusine"),
        ("usine", "0005_add_missing_indexes"),
        ("ventes", "0010_ticket_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="entreprise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produits",
                to="core.entreprise",
            ),
        ),
        migrations.RunPython(backfill_produits_par_entreprise, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="produit",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produits",
                to="core.entreprise",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name="produit",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "code"),
                name="unique_produit_code_par_entreprise",
            ),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(fields=["entreprise", "nom"], name="produits_pr_entrepr_9e8d17_idx"),
        ),
    ]
