# Generated by Django 5.2.11 on 2026-02-28 18:30

import django.db.models.deletion
import produits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lieu_mouture_enabled'),
        ('produits', '0005_produit_entreprise_tenantize'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='produit',
            new_name='produits_pr_entrepr_6fc36e_idx',
            old_name='produits_pr_entrepr_9e8d17_idx',
        ),
        migrations.AlterField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(default=produits.models._default_entreprise_id, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='core.entreprise'),
        ),
    ]
