# Generated by Django 5.2.11 on 2026-03-10 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_fix_produit_entreprise_default_and_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-id'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
