# Generated by Django 5.2.11 on 2026-03-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_audit_final_constraints'),
        ('produits', '0008_produit_poids_par_sac'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.CheckConstraint(condition=models.Q(('poids_par_sac__isnull', True), ('poids_par_sac__gt', 0), _connector='OR'), name='produit_poids_par_sac_positif'),
        ),
    ]
