# Generated by Django 5.2.11 on 2026-03-18 16:29

import django.db.models.deletion
import produits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_audit_final_constraints'),
        ('produits', '0010_categorie_entreprise'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='categorie',
            new_name='produits_ca_entrepr_7a1c6f_idx',
            old_name='produits_ca_entrep_8f4f7e_idx',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='entreprise',
            field=models.ForeignKey(default=produits.models._default_entreprise_id, on_delete=django.db.models.deletion.PROTECT, related_name='categories_produits', to='core.entreprise'),
        ),
    ]
